// export const restaurantArr = [
//   {
//     id: "481967",
//     resName: "Olio - The Wood Fired Pizzeria",
//     cuisine: [
//       "Pizzas",
//       "Pastas",
//       "Italian",
//       "Fast Food",
//       "Snacks",
//       "Beverages",
//       "Desserts",
//     ],
//     avgRating: 4.1,
//     delieveryTime: 51,
//     costForTwo: "₹300 for two",
//     imgId:
//       "RX_THUMBNAIL/IMAGES/VENDOR/2025/12/24/d082dfab-bb70-4cc6-a96d-17e53076b8ed_481967.JPG",
//     location: "Beside Metro Station",
//   },
//   {
//     id: "650820",
//     resName: "Imperial Multicuisine Restaurant",
//     cuisine: ["Biryani", "Chinese", "Indian", "Kebabs", "Tandoor"],
//     avgRating: 4.3,
//     delieveryTime: 38,
//     costForTwo: "₹400 for two",
//     imgId: "rqlwvsmzcfxbg9u6ajgm",
//     location: "Redhills",
//   },
//   {
//     id: "77905",
//     resName: "Santosh Dhaba Exclusive",
//     cuisine: ["Biryani", "Chinese", "Italian", "Mexican", "Desserts"],
//     avgRating: 4.3,
//     delieveryTime: 45,
//     costForTwo: "₹300 for two",
//     imgId: "jllcesio37olflwnvter",
//     location: "ABids",
//   },
//   {
//     id: "481968",
//     resName: "Capital Multi Cuisine Restaurant",
//     cuisine: ["Haleem", "Biryani", "Kebabs"],
//     avgRating: 3.8,
//     delieveryTime: 35,
//     costForTwo: "₹250 for two",
//     imgId: "ijy2jxi7lfwsebdtazpi",
//     location: "Malakpet",
//   },
//   {
//     id: "59643",
//     resName: "Baskin Robbins - Ice Cream Desserts",
//     cuisine: ["Desserts", "Ice Cream"],
//     avgRating: 4.6,
//     delieveryTime: 38,
//     costForTwo: "₹300 for two",
//     imgId:
//       "RX_THUMBNAIL/IMAGES/VENDOR/2025/4/24/724319b2-8428-4fac-ba3c-f1bc079316ef_59643.JPG",
//     location: "Redhills",
//   },
//   {
//     id: "362596",
//     resName: "Burger King",
//     cuisine: ["Burgers", "American"],
//     avgRating: 4.2,
//     delieveryTime: 40,
//     costForTwo: "₹350 for two",
//     imgId:
//       "RX_THUMBNAIL/IMAGES/VENDOR/2025/6/18/225efc0c-71fb-4e38-b12e-f2447b35e05d_362596.jpg",
//     location: "Attapur",
//   },
//   {
//     id: "797153",
//     resName: "Domino's Pizza",
//     cuisine: ["Pizzas", "Italian", "Pastas", "Desserts"],
//     avgRating: 4.5,
//     delieveryTime: 30,
//     costForTwo: "₹400 for two",
//     imgId:
//       "RX_THUMBNAIL/IMAGES/VENDOR/2025/11/11/c78af160-0e43-47b9-8c48-99818e5e30ac_797153.JPG",
//     location: "Charminar",
//   },
//   {
//     id: "341437",
//     resName: "Onesta",
//     cuisine: ["Italian", "Desserts", "Pizzas", "American", "Snacks"],
//     avgRating: 3.6,
//     delieveryTime: 49,
//     costForTwo: "₹200 for two",
//     imgId:
//       "RX_THUMBNAIL/IMAGES/VENDOR/2025/12/19/c27d82ae-10e4-42df-8f2b-fa4a78f1b4a0_341437.JPG",
//     location: "Banjara Hills",
//   },
// ];
